version: "3.7"

services:
    rwar:
        image: radpenguin/php-apache:latest
        dns:
            - 1.1.1.1
            - 1.0.0.1
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.frontend.rule=Host:rwar.docker"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.port=8080"
            - "traefik.protocol=http"
        networks:
            - default
            - traefik
        privileged: true
        restart: always
        volumes:
            - ./:/var/www/html
            - rwar_node_modules:/var/www/html/node_modules
            - rwar_vendor:/var/www/html/vendor

volumes:
    rwar_node_modules:
    rwar_vendor:

networks:
    traefik:
        external: true
