version: "3.7"

services:
    rwar:
        image: radpenguin/php-apache:latest
        dns:
            - 1.1.1.1
            - 1.0.0.1
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.frontend.rule=Host:rwar.docker"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.port=80"
            - "traefik.protocol=http"
        networks:
            - default
            - traefik
        privileged: true
        restart: unless-stopped
        volumes:
            - ./:/var/www/html

networks:
    traefik:
        external: true
